---

- hosts: my_hosts

  vars:
    autoconf: "{{ playbook_dir | dirname }}"
    user: "{{ lookup('env', 'USER') }}"
    desktop: "{{ lookup('env', 'DESKTOP_SESSION') }}"

  tasks:

  - name: Link configs at ~
    loop:
      - linux/.bashrc
      - linux/.dircolors
      - linux/.gitconfig
      - linux/.tmux.conf
      - vim/.vim
      - vim/.vimrc
    file:
      src: "{{ autoconf }}/{{ item }}"
      dest: "~/{{ item | basename }}"
      state: link
      force: true

  - name: Ensure docker group exists
    group:
      name: docker
      state: present
    become: true
  - name: Ensure current user in docker group
    user:
      name: "{{ user }}"
      groups:
        docker
      append: true
    become: true

  - name: Configure QTerminal
    block:
      - name: Ensure QTerminal colors dir exists
        stat:
          path: /usr/share/qtermwidget5/color-schemes/
        register: qtermcolors
      - name: Copy my QTerminal colorscheme
        when: qtermcolors.stat.exists
        copy:
          src: "{{ autoconf }}/linux/lxqt/QTerminal.colorscheme"
          dest: "{{ qtermcolors.stat.path }}"
        become: true
      - name: Configure QTerminal colors
        when: qtermcolors.stat.exists
        loop:
          - {key: "Term", val: "xterm-256color"}
          - {key: "colorScheme", val: "QTerminal"}
        ini_file:
          path: ~/.config/qterminal.org/qterminal.ini
          section: General
          option: "{{ item.key }}"
          value: "{{ item.val }}"

  - name: Configure LXQT desktop environment
    when: desktop is match(".*/lxqt")
    vars:
      vim_desktop: in-vim.desktop
    block:
      - name: Add open in Vim context to file manager
        file:
          src: "{{ autoconf }}/linux/lxqt/{{ vim_desktop }}"
          dest: "~/.local/share/applications/{{ vim_desktop }}"
          state: link
      - name: Set default file associations for Vim
        loop:
          - text/plain
          - text/markdown
          - text/css
          - text/x-scss
          - text/x-python
          - text/x-python3
          - text/x-makefile
          - application/javascript
          - application/json
          - application/x-yaml
          - application/x-shellscript
        ini_file:
          path: ~/.config/mimeapps.list
          section: Default Applications
          option: "{{ item }}"
          value: "{{ vim_desktop }};"
      - name: Update desktop database
        shell: update-desktop-database
        become: true

